name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0

    - name: Terraform init
      run: terraform init

    - name: Terraform apply
      run: terraform apply -auto-approve

    - name: Deploy script to instances
      run: |
        cp user_data.sh $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        terraform apply -auto-approve
        chmod +x user_data.sh
        ./user_data.sh

    - name: Display outputs
      run: terraform output
